language: python
python:
  - 2.7
install:
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install flask
  - pip install pep8
before_script:
  - pep8 src
script:
  - py.test --cov presence_analyzer src/presence_analyzer/tests.py
after_success:
  - coveralls
